"""PDF report generation for access badge records."""

import io
from collections import defaultdict
from datetime import datetime
from pathlib import Path

from reportlab.lib import colors
from reportlab.lib.enums import TA_JUSTIFY, TA_LEFT, TA_RIGHT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import cm
from reportlab.lib.utils import ImageReader
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

try:
    from PIL import Image

    HAS_PIL = True
except ImportError:
    HAS_PIL = False

DOC_LEFT_MARGIN = 2 * cm
DOC_RIGHT_MARGIN = 2 * cm

FOOTER_CONFIDENTIAL = (
    "This report was generated by the PulseID Access Badge System provided only upon request "
    "from the employee or an authorized authority and is strictly confidential."
)


def _parse_date_only(ts):
    if not ts:
        return None
    if isinstance(ts, datetime):
        return ts.date()
    try:
        if "T" in str(ts):
            return datetime.fromisoformat(str(ts).replace("Z", "+00:00")).date()
        return datetime.strptime(str(ts).strip()[:10], "%Y-%m-%d").date()
    except (ValueError, TypeError):
        return None


def _employee_uuid(uid: str) -> str:
    uid = (uid or "").strip().lower()
    try:
        b = bytes.fromhex(uid)
    except ValueError:
        return uid
    rev = b[::-1]
    xored = bytes(a ^ r for a, r in zip(b, rev))
    return xored.hex()


def _records_by_month(records, default_office: str = "Frisange, LU"):
    seen = set()
    normalized = []
    for r in records:
        d = _parse_date_only(r.get("timestamp"))
        if d is None:
            continue
        name = (r.get("name") or "").strip()
        uid = (r.get("uid") or "").strip()
        key = (name, d)
        if key in seen:
            continue
        seen.add(key)
        normalized.append(
            {
                "Name": name,
                "Employee UUID": _employee_uuid(uid),
                "Access Type": "Card",
                "Office": default_office,
                "Date": d.strftime("%d/%m/%Y"),
            }
        )

    by_month: dict[tuple, list] = defaultdict(list)
    for row in normalized:
        try:
            d = datetime.strptime(row["Date"], "%d/%m/%Y")
            by_month[(d.year, d.month)].append(row)
        except (ValueError, IndexError):
            continue

    result = []
    for y, m in sorted(by_month.keys()):
        label = datetime(y, m, 1).strftime("%B %Y")
        result.append(((y, m), label, by_month[(y, m)]))
    return result


def _table_style():
    return TableStyle(
        [
            ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 10),
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#2c3e50")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.whitesmoke),
            ("ALIGN", (0, 0), (-1, -1), "LEFT"),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#bdc3c7")),
            ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#2c3e50")),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#ecf0f1")]),
            ("LEFTPADDING", (0, 0), (-1, -1), 8),
            ("RIGHTPADDING", (0, 0), (-1, -1), 8),
            ("TOPPADDING", (0, 0), (-1, -1), 6),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ]
    )


def _header_footer(canvas, doc, logo_path=None):
    canvas.saveState()
    page_w, page_h = A4
    header_y = page_h - 2.2 * cm
    logo_h = 0.9 * cm

    if logo_path and Path(logo_path).exists():
        try:
            if HAS_PIL:
                pil_img = Image.open(logo_path)
                if pil_img.mode != "RGB":
                    pil_img = pil_img.convert("RGBA")
                    rgb = Image.new("RGB", pil_img.size, (255, 255, 255))
                    bands = pil_img.split()
                    if len(bands) >= 4:
                        rgb.paste(pil_img, mask=bands[3])
                    else:
                        rgb.paste(pil_img)
                    pil_img = rgb
                buf = io.BytesIO()
                pil_img.save(buf, format="PNG")
                buf.seek(0)
                img = ImageReader(buf)
            else:
                img = ImageReader(str(logo_path))
            img_w, img_ht = img.getSize()
            logo_w = logo_h * (img_w / img_ht) if img_ht else logo_h
            canvas.drawImage(
                img,
                DOC_LEFT_MARGIN,
                header_y - logo_h * 0.2,
                width=logo_w,
                height=logo_h,
                preserveAspectRatio=True,
            )
        except Exception:
            pass

    canvas.setLineWidth(0.5)
    canvas.line(DOC_LEFT_MARGIN, page_h - 2.5 * cm, page_w - DOC_RIGHT_MARGIN, page_h - 2.5 * cm)

    footer_text = getattr(doc, "_footer_confidential", None)
    contact_line = getattr(doc, "_footer_contact", None)
    canvas.setFont("Helvetica", 7)
    canvas.setFillColor(colors.HexColor("#7f8c8d"))
    y_footer = 1.0 * cm

    def draw_wrapped(text, max_chars=170):
        nonlocal y_footer
        words = text.split()
        lines, current = [], []
        for w in words:
            current.append(w)
            if sum(len(x) + 1 for x in current) - 1 > max_chars:
                current.pop()
                lines.append(" ".join(current))
                current = [w]
        if current:
            lines.append(" ".join(current))
        for line in reversed(lines):
            canvas.drawCentredString(page_w / 2, y_footer, line)
            y_footer += 0.32 * cm

    if footer_text:
        draw_wrapped(footer_text)
    if contact_line:
        y_footer += 0.15 * cm
        draw_wrapped(contact_line)
    canvas.setFont("Helvetica", 9)
    canvas.drawCentredString(page_w / 2, 0.5 * cm, f"Page {doc.page}")
    canvas.restoreState()


def build_report_pdf(employee_name, uid, records, company_info=None, logo_path=None, filter_year=None, filter_month=None, office_name=None):
    """
    Build PDF report into a BytesIO buffer.
    records: list of dicts with keys 'name', 'uid', 'timestamp'.
    Returns BytesIO buffer.
    """
    if filter_year is not None and filter_month is not None:
        filtered = []
        for r in records:
            d = _parse_date_only(r.get("timestamp"))
            if d and d.year == filter_year and d.month == filter_month:
                filtered.append(r)
        records = filtered
        if not records:
            raise ValueError(f"No records found for {filter_month:02d}/{filter_year}.")

    by_month = _records_by_month(records, default_office=office_name or "Frisange, LU")
    if not by_month:
        raise ValueError("No valid dated records to report.")

    if filter_year is not None and filter_month is not None:
        period_str = datetime(filter_year, filter_month, 1).strftime("%B %Y")
    else:
        first = by_month[0][1]
        last = by_month[-1][1]
        period_str = first if first == last else f"{first} - {last}"

    pdf_title = f"PulseID - {employee_name} - {period_str}"

    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf,
        pagesize=A4,
        rightMargin=DOC_RIGHT_MARGIN,
        leftMargin=DOC_LEFT_MARGIN,
        topMargin=3.0 * cm,
        bottomMargin=2.2 * cm,
        title=pdf_title,
    )

    company = company_info or {}
    contact_parts = []
    if company.get("phone"):
        contact_parts.append(str(company["phone"]).strip())
    if company.get("email"):
        contact_parts.append(str(company["email"]).strip())
    contact_line = " | ".join(contact_parts) if contact_parts else ""
    doc._footer_confidential = FOOTER_CONFIDENTIAL
    doc._footer_contact = f"For questions or to contact the security officer: {contact_line}" if contact_line else None

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle("ReportTitle", parent=styles["Heading1"], fontName="Helvetica-Bold", fontSize=18, spaceAfter=6, alignment=TA_LEFT)
    intro_style = ParagraphStyle("ReportIntro", parent=styles["Normal"], fontName="Helvetica", fontSize=10, spaceAfter=8, alignment=TA_JUSTIFY)
    body_style = ParagraphStyle("ReportBody", parent=styles["Normal"], fontName="Helvetica", fontSize=10, spaceAfter=6, alignment=TA_JUSTIFY)
    month_style = ParagraphStyle("MonthHeading", parent=styles["Heading2"], fontName="Helvetica-Bold", fontSize=14, spaceBefore=14, spaceAfter=6)
    company_title_style = ParagraphStyle("CompanyTitle", parent=styles["Normal"], fontName="Helvetica-Bold", fontSize=11, spaceAfter=4, alignment=TA_RIGHT)
    company_line_style = ParagraphStyle("CompanyLine", parent=styles["Normal"], fontName="Helvetica", fontSize=10, spaceAfter=2, alignment=TA_RIGHT)

    generated_at = datetime.now().strftime("%d/%m/%Y at %H:%M")
    story = []

    if company:
        cname = (company.get("name") or "").strip()
        if cname:
            story.append(Paragraph(cname, company_title_style))
        addr = company.get("address") or {}
        if isinstance(addr, dict):
            if addr.get("street"):
                story.append(Paragraph(str(addr["street"]).strip(), company_line_style))
            parts = []
            if addr.get("zip"):
                parts.append(str(addr["zip"]).strip())
            if addr.get("city"):
                parts.append(str(addr["city"]).strip())
            if parts:
                story.append(Paragraph(" ".join(parts), company_line_style))
            if addr.get("country"):
                story.append(Paragraph(str(addr["country"]).strip(), company_line_style))
        story.append(Spacer(1, 0.2 * cm))

    story.append(Paragraph("PulseID Access Badge Report", title_style))
    story.append(Spacer(1, 0.3 * cm))
    story.append(
        Paragraph(
            "This document is an access badge report issued by the PulseID Access Badge System. "
            "It lists badge access events for the person in the card named below, for the period covered by the tables. "
            f"This report was generated on {generated_at}. "
            "It is provided for the sole use of the person in the card or an authorized authority and is strictly confidential.",
            intro_style,
        )
    )
    story.append(Paragraph(f"<b>Employee:</b> {employee_name}", body_style))
    story.append(Paragraph(f"<b>Report generated:</b> {generated_at}", body_style))
    story.append(Spacer(1, 0.6 * cm))

    content_width = A4[0] - DOC_LEFT_MARGIN - DOC_RIGHT_MARGIN
    ncols = 5
    col_width = content_width / ncols
    headers = ["Name", "Employee UUID", "Access Type", "Office", "Date"]

    lp = logo_path

    def on_page(canvas, doc):
        _header_footer(canvas, doc, logo_path=lp)

    for _ym, month_label, rows in by_month:
        story.append(Paragraph(month_label, month_style))
        data = [headers] + [[r.get(h, "") for h in headers] for r in rows]
        t = Table(data, colWidths=[col_width] * ncols, repeatRows=1)
        t.setStyle(_table_style())
        story.append(t)
        story.append(Spacer(1, 0.4 * cm))

    doc.build(story, onFirstPage=on_page, onLaterPages=on_page)
    buf.seek(0)
    return buf
